PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

# What are the names of my drivers?
SELECT DISTINCT ?driver ?forename ?surname
WHERE {
  ?driver a :drivers ;
          :drivers_forename ?forename ;
          :drivers_surname ?surname .
}